### PR TITLE
[front] chore: migrate from Create-React-App to Vite

### PR DESCRIPTION
**Pull request by amatissart**
### Description

[create-react-app](https://github.com/facebook/create-react-app) (and its "react-scripts")  is resource-hungry as we observed recently on the "staging" environment, and is no longer maintained. [Vite](https://vitejs.dev/) is a more efficient alternative. The build step needs approximately 1GB of RAM, instead of almost 2GB when using CRA.

To migrate, I more or less followed the procedure described in https://www.robinwieruch.de/vite-create-react-app/
The migration should be mostly transparent. The main differences appear in unit tests, where "jest" is replaced with ["vitest"](https://vitest.dev/) which uses a very similar API. That's why some mocks related to the backend API had to be rewritten to use "vitest-fetch-mock" instead of "fetch-mock-jest".

### Checklist

- [x] I added the related issue(s) id in the related issues section (if any)
  - if not, delete the related issues section
- [x] I described my changes and my decisions in the PR description
- [x] I read the development guidelines of the [CONTRIBUTING.md][development-guidelines]
- [x] The tests pass and have been updated if relevant
- [x] The code quality check pass

[development-guidelines]: https://github.com/tournesol-app/tournesol/blob/main/CONTRIBUTING.md#development-guidelines

### CODE REVIEW

**Comment by amatissart** [comment]
@GresilleSiffle This branch should now be production-ready. And it should solve the resource problem we observed on the staging environment. Feel free to look at it when you have some time, this is not urgent.

**Comment by GresilleSiffle** [comment]
Great :clap: I saw there were more than 8000 lines removed in the file `yarn.lock`, that's a good sign : )

**Comment by baptou12** [comment]
Hello, I can see that the `frontend/READEME.md` is still mentioning "Create React App", it might be worth removing it what do you think? 

https://github.com/tournesol-app/tournesol/blob/4f67ff27b6f15e8a96342b8c73a3b81a6ea763ce/frontend/README.md?plain=1#L1C37-L1C53
https://github.com/tournesol-app/tournesol/blob/main/frontend/README.md?plain=1#L82

**Comment by GresilleSiffle** [comment]
It looks good to me. It was very easy to deploy on a virtual machine.

**Review by GresilleSiffle — APPROVED** [review]

**Comment by amatissart** [comment]
Thanks @baptou12, the README file has been updated.

**Pull request merged**
