### PR TITLE
fixed typo of kaban board to kanban

### PR DESCRIPTION
**Pull request by abhiram11**
P.S. I am new to open source contributions, and am all ears for feedback!

### CODE REVIEW

**Review by aidanjungo — APPROVED** [review]

**Comment by aidanjungo** [comment]
Thank you for the correction

**Comment by abhiram11** [comment]
Thank you aidan, I would like to work more on Tournesol. You can assign me issues regarding Javascript, Frontend, and Backend.

**Comment by lfaucon** [comment]
Hey @abhiram11, what do you think of working on this issue next: #1315

**Comment by abhiram11** [comment]
Hi @lfaucon, I'll be looking into the issue now. Will post updates soon.

**Pull request merged**
