### PR TITLE
Browser extension: compatibility with Manifest v2 and Firefox

### PR DESCRIPTION
**Pull request by amatissart**
Related to #225 

* Back to Manifest v2, as Firefox does not support v3 yet
  https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/
  https://bugzilla.mozilla.org/show_bug.cgi?id=1578284

* More robust access token handling:
  * The token is fetched from extension storage on each request to the API
  * The token is updated in the extension storage during navigation on tournesol.app, without explicit reload. 

* Error handling and feedback in UI: buttons are disabled after the first error, error messages are visible on most actions.

* A few cosmetic changes in the popup:
image

### CODE REVIEW

**Comment by lfaucon** [comment]
@aidanjungo want to test it?

**Comment by aidanjungo** [comment]
For me, it seems good on Firefox, maybe we should just add the "build" script also for Firefox and deploy a version, to be sure everything works fine.

**Comment by amatissart** [comment]
> For me, it seems good on Firefox, maybe we should just add the "build" script also for Firefox and deploy a version, to be sure everything works fine.

The same .zip file should be accepted by both Chrome Web Store and Firefox Add-ons.

**Review by lfaucon — COMMENTED** [review]
I'll spend more time testing it this weekend. Thanks for this work. I didn't see anything wrong reading through the code except for the addRateLater call mentioned on discord.

**Review by lfaucon — APPROVED** [review]
🚢

**Pull request merged**
