### PR TITLE
[front] multi-page lists navigation (#1001)

### PR DESCRIPTION
**Pull request by bbosson**
Refactoring of the Pagination component to present the list of pages.
Allow quick navigation to 3 pages before or 3 pages after.
Ability to go to -100 -10 +10 +100 pages
Added a field to enter the page number.

Pagination on large screens: 
image

Pagination on small screens: 
image

Requested change in issue #1001

### CODE REVIEW

**Comment by GresilleSiffle** [comment]
Thank you @bbosson for this pull request :+1: 

I'm going to review it properly today.

There is something we can already improve: the spacing between the buttons -100 / -10 and +10 / +100. The buttons are currently stuck to each other and the UI will be more beautiful if we use either:
- a spacing of 8 or 16 pixels between them
- or a Material UI button group, https://mui.com/material-ui/react-button-group/

The spacing 8 / 16 has currently my personal preference but we can also try the button group.

**Comment by bbosson** [comment]
Thank you for this first feedback. I am looking forward to the next ones and we can also discuss this at lunchtime. 

I have updated the screenshot.

**Comment by amatissart** [comment]
At first glance, the most visible button on the screenshot is "10 suiv >", whereas the most common action is to go to the next page. Should we also add buttons "+1" and "-1" to go to the next/previous page?

Let's also keep in mind the component should be usable on mobile. On small screens, I would suggest to hide the input field and show less buttons.
image

**Comment by bbosson** [comment]
Pull request closed for next developpement of pagination responsive support

**Comment by GresilleSiffle** [comment]
On mobile we could have a completely different layout. 

Proposition: display the - 100 / - 10 / prev / next / + 10 / +100 on a first line, and the list of pages just below.

To save space on the second line we can reduce the number of page buttons displayed on mobile. To save space on the first line we could replace the labels `prev` / `suiv` maybe by symbols?

What do you think @amatissart @bbosson ?

**Comment by bbosson** [comment]
Absolutely, in fact Louis made exactly the same proposal to the daily.

And don't make the buttons disabled by default.

I remove the Page field on small screens.

**Comment by bbosson** [comment]
I have processed the various feedbacks in a new version. Could you tell me what should be changed now?

Pagination on large screens: 
image

Pagination on small screens: 
image

**Comment by aidanjungo** [comment]
I haven't check the code, just the behavior on every page, it looks great, I just find a small layout issue on the `Rate later` page, with only 4 video on my list, it look like this:

image

 Is it normal that button are display when there is only one page?

**Comment by bbosson** [comment]
> I haven't check the code, just the behavior on every page, it looks great, I just find a small layout issue on the `Rate later` page, with only 4 video on my list, it look like this:
> 
> image
> 
> Is it normal that button are display when there is only one page?

Oh no, I had looked at this point at the beginning but I forgot to retest, I'm correcting.

**Comment by GresilleSiffle** [comment]
Thank you @bbosson for your work. We are currently reviewing the code with the team and we will merge soon.

**Review by GresilleSiffle — APPROVED** [review]

**Pull request merged**
