### PR TITLE
few changes in backend.README.md layout + fix snippet language

### PR DESCRIPTION
**Pull request by Vikka**

### CODE REVIEW

**Comment by Vikka** [comment]
Backend readme change but frontend test fails?

```text
      Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  browser-extension/extension.spec.ts      00:20        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/comparisonPage.ts               00:42        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/login.ts                        00:07        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/myRatedVideosPage.spec.ts       00:16        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/rateLaterPage.ts                00:05        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/recommendationsPage.ts          00:02        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/resetPassword.ts                00:18        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/security/contentSecurityPo      00:01        1        1        -        -        - │
  │    licy.ts                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  frontend/settingsAccountPage.spec.t      00:28        3        2        1        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/settingsProfilePage.spec.t      00:24        2        2        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/signup.ts                       00:06        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 11 failed (9%)                      02:54       26       25        1        -        -  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```

**Comment by Vikka** [comment]
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  browser-extension/extension.spec.ts      00:23        2        1        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/comparisonPage.ts               00:29        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/login.ts                        00:05        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/myRatedVideosPage.spec.ts       00:11        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/rateLaterPage.ts                00:03        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/recommendationsPage.ts          00:02        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/resetPassword.ts                00:14        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/security/contentSecurityPo      00:01        1        1        -        -        - │
  │    licy.ts                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/settingsAccountPage.spec.t      00:18        3        3        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/settingsProfilePage.spec.t      00:17        2        2        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  frontend/signup.ts                       00:05        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 11 failed (9%)                      02:13       26       25        1        -        -  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```
Look random to me...

**Comment by GresilleSiffle** [comment]
Hello @Vikka 

Thanks for spotting the confusion between `python` / `shell`.

If I understood correctly, you are also suggesting to use 80 char instead of 79 in the `.md` files? Unless otherwise noticed I've used 79 until now, old Python habits. I'm always open to change my mind and my practices of course, could you explain more about the choice of 80?

Do not hesitate to write a description in your PR so that we can understand not only the choices you made but the reasons behind them. This greatly help keeping the code base harmonized and coherent. Thank you very much :+1:

**Comment by Vikka** [comment]
@GresilleSiffle No, if a line is 80c or more, it's a mistake ! (except for links, but I will make a commit about it.)
I will put more details in my current and future PR, sure :)

**Review by lfaucon — APPROVED** [review]
Looks good

**Pull request merged**
