### PR TITLE
Better "Rate Later" button: checkmark icon when done

### PR DESCRIPTION
**Pull request by maximedrouhin**
# Before
image

image

# After
image

image

# Why?

This makes it more obvious that:
1. the action was completed
2. the button is not actionable any more.

So this change makes the interface more intuitive to the user.

### CODE REVIEW

**Review by GresilleSiffle — APPROVED** [review]
It works!

Thank you : ) Let's wait for the tests to run before merging.

**Comment by GresilleSiffle** [comment]
Oops, I forgot to update the patch version in the manifest.

**Comment by maximedrouhin** [comment]
All checks have passed!

**Comment by maximedrouhin** [comment]
> Oops, I forgot to update the patch version in the manifest.
@GresilleSiffle About updating the patch version in the manifest, do you think it could be automated with GitHub Actions? Should I write an issue about it?

**Comment by GresilleSiffle** [comment]
> @GresilleSiffle About updating the patch version in the manifest, do you think it could be automated with GitHub Actions? Should I write an issue about it?

It would be great! If the version is updated by the GitHub Actions, we need a way to tell the CI that those changes represent a minor release, those a patch release. Or maybe the CI can always increase the patch version except if the version has been manually updated in a commit?

I never dived into GitHub Actions so I can't evaluate the complexity. Nevertheless, we can still create an issue with a link to this comment : )

Thank you @maximedrouhin

**Comment by maximedrouhin** [comment]
@GresilleSiffle I created an issue: https://github.com/tournesol-app/tournesol/issues/1618

**Pull request merged**
