### PR TITLE
[back] Include a metadata and remove root folder in the public dataset

### PR DESCRIPTION
**Pull request by aidanjungo**
#1396

### CODE REVIEW

**Comment by aidanjungo** [comment]
Pending questions:

- What is the best way to include the commit hash in the metadata?
- Which algo parameter should be included in the metadata?
- Should be gather all the these parameters in a single file? (maybe not relevant if we decide to create a `tournesol-algo` package)

**Comment by GresilleSiffle** [comment]
> Should be gather all the these parameters in a single file? (maybe not relevant if we decide to create a tournesol-algo package)

If the question is: should we write all those parameters in a single metadata file? my answer is: yes I think it's useful for now. Even if the algorithms are part of an external python package, they might be configurable, and in this case providing the configuration in the dataset output is useful.

**Comment by GresilleSiffle** [comment]
> What is the best way to include the commit hash in the metadata?

We can write the hash in the `/etc/tournesol/settings.yml` in a Django setting `TOURNESOL_VERSION`.

**Comment by aidanjungo** [comment]
@amatissart if you have idea of other algo parameters that we should include in the metadata, let me know

**Review by amatissart — APPROVED** [review]
LGTM

@aidanjungo  I added a few more parameters defined in "mehetan/run.py" and "trust_algo.py".  I also moved `OVER_TRUST_BIAS` and `OVER_TRUST_SCALE`  to "mehestan" as they are used when computing global scores and are more related to Mehestan than Byztrust.

In the longer term, we may want to persist such metadata in the database, for a better traceability about the past runs. As is, there is no guarantee that the values exported in "metadata.json" were the same when scores were computed.

**Pull request merged**
