### PR TITLE
[front] feat: add the sub-sample tab to the entity selector

### PR DESCRIPTION
**Pull request by GresilleSiffle**
**related issues** #1750

**we could merge** #1765 first, then rebase those changes on top of `main`

---

### Description

This PR adds the sub-sample tab to the entity selector.

When designing this tab, we talked about adding visual elements to show that the video are ordered, from the most recommended to the least recommended. It could be the personal score, the bucket number, etc. For now, no visual indications have been added.

#### Preview

sub

#### Personal score

**edit** this PR implements the alternative 4 (see below)

alt 1

Here is how we can represent an individual score of a specific criterion, in a way that it appears different than a collective score to avoid any confusion.

- the main icon represents a person (instead of a criterion)
- the secondary icon represents a criterion
- the secondary icon is smaller than the main icon
- (the secondary icon could be displayed slightly on top of the main icon to free some horizontal space, we just need to check if the icons license allows us to do so ; we could also create our own "face" icon)

sub

---

alt 2

capture

---

alt 3

capture

---

alt 4

capture

### Checklist

- [x] I added the related issue(s) id in the related issues section (if any)
  - if not, delete the related issues section
- [x] I described my changes and my decisions in the PR description
- [x] I read the development guidelines of the [CONTRIBUTING.md][development-guidelines]
- [ ] The tests pass and have been updated if relevant
- [x] The code quality check pass

[development-guidelines]: https://github.com/tournesol-app/tournesol/blob/main/CONTRIBUTING.md#development-guidelines

### CODE REVIEW

**Comment by GresilleSiffle** [comment]
Regarding the design, I finally opted for the alternative 4.

**Comment by lfaucon** [comment]
I don't thiink the name "sub-sample" & "échantillon" is good for the colonne.

What do you think of "Your ratings" & "Vos scores" ?

Any other idea?

**Comment by lfaucon** [comment]
> Regarding the design, I finally opted for the alternative 4.

I also like alt 4 the best

**Comment by GresilleSiffle** [comment]
I like the proposition "Your ratings" and "Vos scores", I like even better "Your scores" and "Vos scores". If I remember correctly we tried to use rating to refer to the rating given by the users (between -10 / + 10 for a criterion), and the score to refer to the computed score by the algorithm.

**Comment by lfaucon** [comment]
> If I remember correctly we tried to use rating to refer to the rating given by the users (between -10 / + 10 for a criterion)

No, I don't think so. In the code `rating` refers to single video ratings and are not within the range [-10, 10] unlike `comparison`. Then we have `rating.criteria_score` and `comparison.criteria_scores`

**Review by amatissart — APPROVED** [review]

**Pull request merged**
