### PR TITLE
 [front] feat: Add options to share on social media from video cards/analysis page

### PR DESCRIPTION
**Pull request by ShinseiNova**
**related to #1606**
image
image

### CODE REVIEW

**Comment by GresilleSiffle** [comment]
I like the new design, and I like to have the compare and add to rate-later buttons here instead of in the metadata box.

- the buttons are bigger, easier to see, harder to miss
- their position reminds me of the YouTube layout
- they feel more engaging to me

I'd be OK to create a new UX rule in the front end:
- when a video is displayed with VideoCard containing a thumbnail, the actions are displayed in the metadata box
- when a video is meant to be watched (only one player on the screen, wide format), the actions are displayed under the player to match the YouTube layout

**Comment by GresilleSiffle** [comment]
Review:

- [ ] convert the CopyContent icon to a share icon (deploying the old menu allowing the users to copy the page address)
- [ ] add a new entry to this menu to copy the "share message"

**Comment by lfaucon** [comment]
To support both copying the address and copying a message to be share on Social Networks
Screenshot 2023-07-06 at 12 24 34

**Comment by lfaucon** [comment]
> Do we want something like that ? Or should we keep a separate button for Twitter

Unsure.
I like the suggestion.
Seeing the blue Share on Twitter button that you propose in the first design may be helpful for the sharing feature to be easily discovered.

**Review by GresilleSiffle — APPROVED** [review]

**Pull request merged**
