### PR TITLE
Add Bar chart on video analysis page

### PR DESCRIPTION
**Pull request by sigmike**
Related issue: #626

Initial attempt to add the Bar chart:

image

Moving the ticks in the middle doesn't seem possible with recharts. It may be possible to solve that by making 2 aligned charts.

Most of the code is copied from the Radar chart. Some of it should be refactored if both charts are going to stay.

### CODE REVIEW

**Comment by lfaucon** [comment]
Screenshot 2022-03-18 at 22 27 53

Pushed a commit to improve the layout, including:
- centering the icons
- removeing the margin created by the left Y-Axis
- a tooltip that displays the exact values

**Review by lfaucon — APPROVED** [review]
LGTM!

The design of the Video Analysis page will be in any case improved as part of #694

**Comment by sigmike** [comment]
> centering the icons

But this hides small bars. We don't care? I can try the aligned dual chart.

**Comment by lfaucon** [comment]
I discussed yesterday evening with @aidanjungo and @amatissart and it did not seem to important that very small scores are hidden. The tooltip helps to see the exact value.

Unless you think it wll be very easy to do the double bar chart, I'd recommend keeping this visualization as it is now and revisiting it only later if we feel the need.

**Pull request merged**
