### PR TITLE
[extension] Add search related recommendations

### PR DESCRIPTION
**Pull request by FabienRoger**
See #431

Add search related recommendations with the structure of the recommendations from the main page.
I think it is relevant to do it like this and not present the results as search "results" because very often, the results are not relevant at all.

image

image

### CODE REVIEW

**Comment by FabienRoger** [comment]
The tests failed for a very weird reason

> Run actions/upload-artifact@v1
> Error: Path does not exist /home/runner/work/tournesol/tournesol/tests/cypress/screenshots
> Error: Exit code 1 returned from process: file name '/home/runner/runners/2.285.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.

**Review by lfaucon — COMMENTED** [review]
Not reviewed yet, but very much looking forward to this feature! Thanks

**Comment by GresilleSiffle** [comment]
We are going to review & merge the https://github.com/tournesol-app/tournesol/pull/417 before reviewing this one.

**Comment by GresilleSiffle** [comment]
Hello!

This feature is very useful!

Considering the current limitation of our search system, I would not display search results when the number of typed characters in the YT search bar is strictly inferior to three. Because a " bunch " of videos can have a matching combination of two characters. 

#### future considerations

Display the extension panel, even if there are no result in the currently selected language, because there can be results in another language and for now, only the extension panel allows to select a language. I'll add a `discussion` ticket when this PR is merged.

**Comment by lfaucon** [comment]
I think we should try to target this design s othat it feels much more integrated within Youtube.

Screenshot 2022-01-18 at 23 05 57

**Pull request closed without merging**
