### PR TITLE
Run ML on each Poll

### PR DESCRIPTION
**Pull request by farnots**
Linked to #572 

⚠️ If the PR https://github.com/tournesol-app/tournesol/pull/561 is merged before, some conflict should be fixed.

### CODE REVIEW

**Comment by amatissart** [comment]
@farnots Even if "video" is currently the only type that can be used in a Poll, it should still be possible to set up a test case where a second poll about videos would be created, possibly with some new criterias on videos. Then, a test could check that `EntityCriteriaScore` instances are correctly created to cover all pairs of (poll, criteria).

**Review by lfaucon — APPROVED** [review]
Apart from the lack of test, this works for me :)

**Comment by farnots** [comment]
> @farnots Even if "video" is currently the only type that can be used in a Poll, it should still be possible to set up a test case where a second poll about videos would be created, possibly with some new criterias. Then, a test could check that `EntityCriteriaScore` instances are correctly created to cover all pairs of (poll, criteria).

I added a factory to create a new poll and test the code against it

**Comment by amatissart** [comment]
@farnots Now that #561 has been merged and deployed, you can solve the conflicts on this branch.

**Comment by farnots** [comment]
@amatissart @lfaucon OK for review

**Pull request merged**
