### PR TITLE
fix the HTML formatting of privacy policy page

### PR DESCRIPTION
**Pull request by GresilleSiffle**
related to #124

### CODE REVIEW

**Review by sergeivolodin — COMMENTED** [review]
Looks good, can you attach a screenshot with how it looks now? This one gives one screenshot for the whole page: http://gofullpage.com/

**Comment by GresilleSiffle** [comment]
I saw the frontend uses Material UI, so I think the usage of the [Typography](https://material-ui.com/components/typography/) component instead of the classic `<p>` tag should be better.

This way, the look and feel of the Privacy Policy page will be consistent with the rest of the site.

What do you think ?

**Comment by GresilleSiffle** [comment]
The result with the `<p>` tag

privacy_policy_with_p

**Comment by GresilleSiffle** [comment]
Here is a new screen shot with the usage of `<Typography paragraph component='p'>` instead of `<p>`.

The result is consistent with the other paragraphs in the application.

privacy_policy_with_typography

**Comment by sergeivolodin** [comment]
Screenshots look good, thank you!

Right now tests fail because of lint issues, you can fix them with `npm run eslintFix`.
Generally, you can go to the workflow Details page and scroll down to the last message

image

**Comment by GresilleSiffle** [comment]
> Right now tests fail because of lint issues, you can fix them with npm run eslintFix.

Thanks for the trick ! Sorry I didn't know there were a process involving eslint.

Are there other commands I should run before making a commit? (to be sure I didn't break anything)

**Comment by sergeivolodin** [comment]
> > Right now tests fail because of lint issues, you can fix them with npm run eslintFix.
> 
> Thanks for the trick ! Sorry I didn't know there were a process involving eslint.
> 
> Are there other commands I should run before making a commit? (to be sure I didn't break anything)

Generally you just run `./tests.sh` (does the same thing as github CI) and manually test that everything works (test wouldn't catch things like broken layout)

**Comment by sergeivolodin** [comment]
Thank you for the edit @GresilleSiffle !

**Pull request merged**
